function roc = cor2roc(cor)
    assert(iscell(cor) && all(cellfun(@iscell, cor)) && ...
           iscolumn(cor) && ...
           numel(unique(cellfun(@(r) size(r, 2), cor))) == 1, ...
           'input is not a "cell column" of (equal-width) "cell rows"');
    roc = num2cell(cat(1, cor{:}), 1);
end
