function cor = roc2cor(roc)
    assert(iscell(roc) && all(cellfun(@iscell, roc)) && ...
           isrow(roc) && ...
           numel(unique(cellfun(@(c) size(c, 1), roc))) == 1, ...
           'input is not a "cell row" of (equal-height) "cell columns"');
    cor = num2cell(cat(2, roc{:}), 2);
end
